name: Feature Branch

on:
  push:
    branches-ignore:
      - 'release*'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.2
      - name: Maven Build
        run: ./mvnw clean package